language: node_js
node_js:
  - 6
addons:
  code_climate:
    repo_token: a34046e71ff75ed4cc60763d5a6e6007b9ed37117a1911b465a177b3e910eda1
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < ./test/unit/coverage/lcov.info
