language: node_js
node_js:
  - 6
addons:
  code_climate:
    repo_token: a34046e71ff75ed4cc60763d5a6e6007b9ed37117a1911b465a177b3e910eda1
after_script:
  - pwd
  - codeclimate-test-reporter < ./coverage/lcov.info
